[features]
seeds = false
skip-lint = false
[programs.localnet]
gm_maker = "Hqf7x3NE8ajoipvRofrXuQ8D2qEX9vWbeNumbCGtXcHH"

[programs.devnet]
gm_maker = "Hqf7x3NE8ajoipvRofrXuQ8D2qEX9vWbeNumbCGtXcHH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/anamansari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
